# naviOS/protocol7 - nightshadeNeon (tmux)
# ( place: $HOME/.config/tmux/tmux.conf )
# ---------------------------------------------------------

# --- core prefixes
set -g prefix C-Space
unbind C-b
bind C-Space send-prefix

# --- terminal overrides
set -g default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"

set -sg escape-time 0
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g status-position top

# --- keybinds
bind Q kill-pane
bind f resize-pane -Z
bind Enter new-window -c "#{pane_current_path}"
bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"

# navigation
bind Left select-pane -L
bind Down select-pane -D
bind Up select-pane -U
bind Right select-pane -R

# swap panes
bind S-Left swap-pane -s '{left-of}'
bind S-Down swap-pane -s '{down-of}'
bind S-Up swap-pane -s '{up-of}'
bind S-Right swap-pane -s '{right-of}'

# --- status bar (inspired by wiredWM)
set -g status-interval 1
set -g status-style 'bg=default'
set -g status-justify left

set -g status-left-length 150
set -g status-right-length 150

# left: workspaces
set -g status-left "#[fg=#39ff14,bg=#0f0f0f,bold] Ø #[fg=#ff10f0,bg=default] #S #[fg=#444444,bg=default] "

# right: indicators (Prefix/Zoom) + clock/date module
# PREFIX: #0000ff | ZOOM: #39ff14
set -g status-right "#{?client_prefix,#[fg=#0000ff] PREFIX ,}#{?window_zoomed_flag,#[fg=#39ff14] ZOOM ,} #[fg=#39ff14,bg=#0f0f0f,bold] %H:%M #[fg=#ff10f0,bg=default]#[fg=#0f0f0f,bg=#ff10f0,bold] %A, %B %d "

# workspaces
setw -g window-status-separator "  "
setw -g window-status-format "#[fg=#444444]#I:#W"
setw -g window-status-current-format "#[fg=#ff10f0,bg=#0f0f0f,bold] #I:#W "

# --- borders/dimming
# --- (inactive panes are dimmed)
set -g pane-active-border-style "fg=#ff10f0,bg=default"
set -g pane-border-style "fg=#39ff14,bg=default"

setw -g window-style 'fg=#666666'
setw -g window-active-style 'fg=#ffffff'

# --- resize mode
bind r switch-client -T resize
bind -T resize Left resize-pane -L 10
bind -T resize Down resize-pane -D 10
bind -T resize Up resize-pane -U 10
bind -T resize Right resize-pane -R 10

# --- reload
bind C-r source-file ~/.config/tmux/tmux.conf \; display-message "reloaded!"
